name: Checkout repo
on: [push]
jobs:
  checkout-repo-manually:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a
      - name: Checkout repo manually
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List files after checkout
        run: ls -a
  checkout-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a
      - name: Checkout repo with actions
        uses: actions/checkout@v4
      - name: List files after checkout
        run: ls -a
